Add User and stories around
evmorov/just-ask pull request #3
Opened 2016-11-18 20:20 UTC by evmorov

- Пользователь может создавать вопрос
- Пользователь может просматривать список вопросов
- Пользователь, находясь на странице вопроса, может написать ответ на вопрос (т.е. форма нового ответа должна быть прямо на странице вопроса, без перехода на другую страницу)
- Пользователь может просматривать вопрос и ответы к нему
- Пользователь может войти в систему
- Пользователь может выйти из системы
- Пользователь может зарегистрироваться в системе
- Только аутентифицированный пользователь может создавать вопросы и ответы
- Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ

2016-11-19 09:31 UTC, vkurennov requested changes
Исправь замечания

2016-11-19 09:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.user == current_user
1. Сравнивать лучше по id, чтобы не тянуть ассоциацию user из базы, ведь она нам не нужна, нам надо понять только автор это или нет.
2. Такая проверка будет нужна часто, вынеси ее в метод `User#author_of?`

2016-11-19 09:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    render 'questions/show'
Почему render, а не redirect? При редиректе данные из базы загрузятся заново, т.е. удаленного ответа не будет. А в случае рендера, в памяти еще может оставаться удаленный ответ, что может привести к ошибкам. С рендером тоже можно работать, если аккуратно, но здесь проще сделать редирект и не маяться.

2016-11-19 09:31 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.destroy if @question.user == current_user
Замени на метод `User#author_of?`

2016-11-19 09:31 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    redirect_to questions_path
Если вопрос не удален, то надо бы какое-то сообщение написать

2016-11-19 09:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.user == current_user
Да, и если ответ не удален, то надо бы что-то написать юзеру по этому поводу

2016-11-19 09:31 UTC, vkurennov commented on app/views/questions/index.html.slim
> +      a href=question_path(question) #{question.title}
Используй хелпер link_to, а то как-то ни рыба ни мясо получается. и не хтмл и не руби.

2016-11-19 09:31 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if @question.user == current_user
Замени на `User#author_of?`

2016-11-19 09:31 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    - if answer.user == current_user
Замени на `User#author_of?`

2016-11-19 09:31 UTC, vkurennov commented on spec/acceptance/list_of_questions_spec.rb
> +    create(:question, title: 'First')
Лучше создать список из 5-10 разных вопросов (используй sequence в фабриках) и проверить их все на странице

2016-11-19 09:31 UTC, vkurennov commented on spec/acceptance/remove_answer_spec.rb
> +      @me = create(:user)
Используй let/given вместо инстанс-переменных

2016-11-19 09:31 UTC, vkurennov commented on spec/acceptance/remove_answer_spec.rb
> +      within(:xpath, "//p[text()='#{@my_answer.body}']") do
Лучше css-селекторы, они легче читаются

2016-11-19 09:31 UTC, vkurennov commented on spec/acceptance/remove_answer_spec.rb
> +        expect(page).to_not have_selector(:link_or_button, 'Remove')
А тут просто `to_no have_link`

2016-11-19 09:31 UTC, vkurennov commented on spec/acceptance/sign_out_spec.rb
> +  scenario 'Sign out' do
Тут нужен сценарий, что незалогиненный юзер не видит этой ссылки

2016-11-19 09:31 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'POST #create' do
Тут надо проверить, что ответ связывается с залогинненым юзером

2016-11-19 09:31 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        }.to change(answer.question.answers, :count).by(-1)
Достаточно просто `question.answers`

2016-11-19 09:31 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        }.to change(answer.question.answers, :count).by(0)
`to_not change`

2016-11-19 09:31 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'POST #create' do
Надо проверить, что вопрос связывается с залогиненным юзером

2016-11-19 09:31 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, params: { id: question } }.to change(Question, :count).by(0)
`to_not change`

2016-11-19 12:33 UTC, evmorov commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.user == current_user
> Да, и если ответ не удален, то надо бы что-то написать юзеру по этому поводу

У меня в UI нет кнопок удаления у чужих вопросов. С помощью acceptance тестов не могу это проверить. Всё равно хорошо бы сделать?

2016-11-19 12:58 UTC, evmorov commented on app/controllers/questions_controller.rb
> +    redirect_to questions_path
У меня в UI нет кнопок удаления у чужих вопросов. С помощью acceptance тестов не могу это проверить. Всё равно хорошо бы сделать?

2016-11-19 13:33 UTC, evmorov commented on app/views/questions/index.html.slim
> +      a href=question_path(question) #{question.title}
Воу-воу. Как это сюда попало?

2016-11-19 15:55 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.user == current_user
Да, либо, что самое правильное, отдать 403 статус (и протестировать это в тестах контроллера)

2016-11-19 16:01 UTC, vkurennov requested changes

2016-11-19 16:01 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question, error: 'You can remove only your answer'
редирект один и тот же, зачем в условия выносить? Лучше в else  просто флеш-сообщение установить, а сам редирект сделать после условия

2016-11-19 16:01 UTC, vkurennov commented on app/models/user.rb
> +    id == obj.user.id
Такое сравнение все также неэффеквтивно, что и сравнение по объектам. Ведь по-прежнему, мы сначала грузим ассоциацию user из базы у объекта. Но ведь в самом объекте есть поле user_id, обращаясь к которому мы и получим нужное значение без лишнего запроса к базе

2016-11-19 16:01 UTC, vkurennov commented on app/views/questions/index.html.slim
> +      = link_to question.title, question_path(question)
Кстати, можно вторым параметром просто question писать, это то же самое

2016-11-19 16:01 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        }.to_not change(question.answers, :count)
здесь должно быть Answer, чтобы точно быть уверенным, что никакой ответ не удалился

2016-11-19 16:01 UTC, vkurennov commented on spec/models/user_spec.rb
> +describe User, type: :model do
Где тесты на метод author_of?

2016-11-19 17:25 UTC, evmorov commented on app/controllers/answers_controller.rb
> +      redirect_to question, error: 'You can remove only your answer'
Ой, точно

2016-11-19 17:31 UTC, evmorov commented on app/models/user.rb
> +    id == obj.user.id
Ёлки палки. Ничего себе я протормозил

2016-11-19 17:33 UTC, evmorov commented on spec/models/user_spec.rb
> +describe User, type: :model do
Ой, точно

2016-11-19 22:22 UTC, evmorov commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.user == current_user
@vkurennov, я разобрался что это можно сделать с помощью `head :forbidden` и понял как проверить. Должен ли controller дополнительно что-то делать или одного `head :forbidden` достаточно? Или ты имел в виду что нужно отрендерить страницу с ошибкой со статусом 403?

P.S. пока что сделал просто flash, чтобы закончить данный модуль

2016-11-20 07:56 UTC, vkurennov approved these changes

2016-11-20 07:56 UTC, vkurennov commented on spec/models/user_spec.rb
> +    it 'raises NoMethodError if an argument does not repond to #user_id' do
Это лишнее, т.к. тут тестируется стандартное поведение руби, когда он не может найти метод. Было бы лучше (хотя и не обязательно) сделайть фейковый объект с методом user_id и проверить, что он работает как надо.

2016-11-20 12:37 UTC, evmorov commented on spec/models/user_spec.rb
> +    it 'raises NoMethodError if an argument does not repond to #user_id' do
А если бы внутри метода был использован safe navigation (try)? Тогда бы метод возвращал nil. Я хотел показать этим тестом не определённый exception, а то что тут exception, если придёт что-то не то. Или таки излишне?

2016-11-20 12:41 UTC, merged

2016-11-20 12:55 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.user == current_user
Достаточно только head :forbidden, это и есть пустой ответ с нужным статусом.

2016-11-20 12:56 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    redirect_to questions_path
Это надо проверить с помощью тестов контроллера.

2016-11-20 12:59 UTC, evmorov commented on app/controllers/questions_controller.rb
> +    redirect_to questions_path
Да, я понял это. Это уже сделал.

2016-11-21 12:05 UTC, vkurennov commented on spec/models/user_spec.rb
> +    it 'raises NoMethodError if an argument does not repond to #user_id' do
Да, излишне, т.к. это стандартное поведение. Скорее, надо было бы показать, что метод возвращает nil, а не выкидывает исключение, если бы использовали trye