More ajax
evmorov/just-ask pull request #5
Opened 2016-11-27 21:33 UTC by evmorov

- Только автор может отредактировать свой вопрос
- Только автор может отредактировать свой ответ
- Переделать удаление ответов на ajax
- Автор вопроса может выбрать лучший ответ для своего вопроса (лучший ответ может быть только 1)
- Автор вопроса может выбрать другой ответ как лучший, если у вопроса уже выбран лучший ответ.
- Если у вопроса выбран лучший ответ, то он отображается первым в списке ответов.

![more-ajax](https://cloud.githubusercontent.com/assets/1059480/20652004/38983c3a-b502-11e6-9e3d-c11bfaeb2ab2.gif)

2016-11-28 11:17 UTC, vkurennov requested changes

2016-11-28 11:17 UTC, vkurennov commented on app/controllers/answers_controller.rb
Всю эту логику нужно вынести в метод модели и обернуть в [транзакцию](Всю эту логику нужно вынести в метод модели и обернуть в транзакцию), чтобы изменения были атомарными.

2016-11-28 11:17 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    the_best_answer = @answer.question.answers.find(&:best)
Используй where для задания условий выборки.

2016-11-28 11:17 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      the_best_answer.best = false
Лучше использовать update

2016-11-28 11:17 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.best = !@answer.best
И тут лучше update.

2016-11-28 11:17 UTC, vkurennov commented on app/views/answers/best.js.erb
> +function removeTheBestAnswer() {
Сами функции лучше объявить вне ответа, т.е. где-то в js-ассетах, а здесь их вызывать. Только надо учесть [проблему с турболинками](http://connect.thinknetica.com/t/ajax-turbolinks/955).

2016-11-28 11:17 UTC, vkurennov commented on app/views/answers/update.js.erb
> +  $('#answers').html('<%= j render @question.answers %>');
Нет, надо заменять только измененный ответ, а не рендерить весь список повторно.

2016-11-29 07:38 UTC, vkurennov requested changes

2016-11-29 07:38 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question, error: 'You can edit only your answer'
Ну и редирект тут лишний все же, толку от него нет. Если ajax-запрос, то лучше рендерить какую-нибудь js-вьюху, которая покажет флеш-сообщение пользователю.

2016-11-29 07:38 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question, error: 'You can remove only your answer'
И тут редирект не нужен, раз у тебя через ajax удаление

2016-11-29 07:38 UTC, vkurennov commented on app/models/answer.rb
> +      the_best_answer.update(best: false) if the_best_answer
транзакция откатывается только в случае исключения, поэтому, чтобы она работала, надо использовать методы `update!`

2016-11-29 07:38 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  = content_tag(:div,
Есть удобный хелпер div_for для этого

2016-11-29 07:38 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.best).to be(false)
В юнит-тестах дейтсвует правило "один тест - один exepct", раздели этот тест на 2

2016-11-29 07:38 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(best_answer.best).to be(false)
Здесь достаточно только этой проверки, т.к. изменение флага у того объекта, у которого вызван метод ты уже проверил.

2016-11-29 07:38 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    it 'unselects the best answer if it is already the best' do
И это тоже проверено уже, так что тест лишний

2016-11-29 08:55 UTC, evmorov commented on spec/models/answer_spec.rb
> +    it 'unselects the best answer if it is already the best' do
Я его немного переименовал. Но тут он не лишний.

Получается так:
- первые тесты проверяют toggle
- следующий тесты проверяет то, что если мы выбираем новый best answer, то предыдущий уже не best
- этот тест проверяет то, что если мы делаем ответ как the best, то другие не делаются the best. Код мог бы быть таким, что ко всем ответам применяется toggle и в теории предыдущие тесты проходили бы

2016-11-29 08:57 UTC, evmorov commented on app/controllers/answers_controller.rb
> +      redirect_to @question, error: 'You can edit only your answer'
Сделал `head :forbidden`, который ты назвал лучшим решением https://github.com/evmorov/just-ask/pull/3/files/137ececb7de8aa70d710d73e78a7df90d41ebc72#diff-605e1876b7ec21834383163392c37b58
, т.к. кнопки edit и delete всё равно не отображаются

2016-11-29 08:57 UTC, evmorov commented on app/controllers/answers_controller.rb
> +      redirect_to question, error: 'You can remove only your answer'
Сделал `head :forbidden`, который ты назвал лучшим решением https://github.com/evmorov/just-ask/pull/3/files/137ececb7de8aa70d710d73e78a7df90d41ebc72#diff-605e1876b7ec21834383163392c37b58
, т.к. кнопки edit и delete всё равно не отображаются

2016-11-29 08:58 UTC, evmorov commented on app/views/answers/_answer.html.slim
> +  = content_tag(:div,
"The `div_for` method has been removed from Rails. To continue using it, add the `record_tag_helper` gem to your Gemfile". Пришлось добавить. Но это стоит того, хороший helper.

2016-11-29 09:47 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  = content_tag(:div,
А, да, точно, его же из core выпилили. Хотя, хороший метод был :-)

2016-11-29 09:47 UTC, vkurennov approved these changes

2016-11-29 11:50 UTC, merged