Votes
evmorov/just-ask pull request #7
Opened 2016-12-11 22:53 UTC by evmorov

- Аутентифицированный пользователь может голосовать за понравившийся вопрос/ответ
 Пользователь не может голосовать за свой вопрос/ответ
- Пользователь может проголосовать "за" или "против" конкретного вопроса/ответа только один раз (нельзя голосовать 2 раза подряд "за" или "против")
- Пользователь может отменить свое решение и после этого переголосовать.
- У вопроса/ответа должен выводиться результирующий рейтинг (разница между голосами "за" и "против")

2016-12-12 12:41 UTC, vkurennov requested changes

2016-12-12 12:41 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    @votable.upvote(current_user.id)
Зачем id передавать? Передвай сам объект current_user, он же уже и так в память загружен.

2016-12-12 12:41 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +            vote_state: @votable.vote_state(current_user.id),
Этот статус можно передавать из экшенов контроллера не делая запросов к базе

2016-12-12 12:41 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    return if user.id == user_id
А зачем грузить самого пользователя из базы, если достаточно их id сравнить. Да и у тебя есть метод для этого в таблице User. Правда, ты передаешь зачем-то id, когда у тебя есть возможность передать объект

2016-12-12 20:30 UTC, evmorov commented on app/controllers/concerns/voted.rb
> +            vote_state: @votable.vote_state(current_user.id),
Речь о том, чтобы перенести [метод vote_state(user)](https://github.com/evmorov/just-ask/pull/7/files#diff-32c1bf77ef263689d204322f784e85efR19) из модели в контроллер?

Если да, то он у меня [используется во view](https://github.com/evmorov/just-ask/pull/7/files#diff-85277df00fb0462e0c18229c54ceae28R4), чтобы отобразить текущий статус голосования для данного пользователя. Если я его перенесу в controller, то при нажатии на голосование, статус голосования (зелёная стрелочка вверх или красная стрелочка вниз) будут отображаться, но до обновления страницы. Если я хочу сделать, чтобы статус голосования отображался всегда, то мне придётся данный метод продублировать во view (ну или в модели как сейчас).

Оно используется не просто для статуса всего голосования, а для статуса голосования для данного конкретного пользователя, чтобы пользователь видел как он отдал свой голос.

![vote](https://cloud.githubusercontent.com/assets/1059480/21115485/7e28e832-c0c2-11e6-9b46-8ea9e53f5afd.gif)

Или #vote_state настолько плохо смотрится в модели, что лучше его вынести такой ценой?

2016-12-13 12:20 UTC, vkurennov approved these changes

2016-12-13 20:58 UTC, merged